on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04, macos-latest]
    steps:
    - uses: actions/checkout@v1      
    - name: Run Continuous Integration
      run : ./ContinuousIntegration/ContinuousIntegration.ps1
      shell: pwsh